import { useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import Greet from "@/components/greet/Greet";
import Button from "@/components/button/Button";
import List from "@/components/list/list";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [arr, setArr] = useState(["apple"]);

  const addHandler = () => {
    setArr([...arr, "New Item"])
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Greet />
      <List arr={arr} />
      <Button click={addHandler}>Add</Button>
    </>
  );
}
